default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: plataforma-itd_development

test:
  <<: *default
  database: plataforma-itd>_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
